name: CI

on:
  push:
    branches:
      - main
      - develop
      - CI_DEV
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # Restore Core tests
    - name: Restore Core
      run: dotnet restore FastMath.Core.Tests/FastMath.Core.Tests.csproj

    # Build Core tests
    - name: Build Core
      run: dotnet build FastMath.Core.Tests/FastMath.Core.Tests.csproj --configuration Release --no-restore

    # Run Core unit tests
    - name: Run Core unit tests
      run: dotnet test FastMath.Core.Tests/FastMath.Core.Tests.csproj --configuration Release --no-build

    # Install MAUI Android workload
    - name: Install MAUI Android workload
      run: dotnet workload install maui

    # Restore MAUI Android
    - name: Restore MAUI Android
      run: dotnet restore

    # Build MAUI Android
    - name: Build FastMath MAUI Android
      run: dotnet build FastMath/FastMath.csproj -f net10.0-android -c Release --no-restore
